"""
Hotel Intel — Recap Generator.

Takes processed data, builds a prompt following the recap template style,
sends it to the configured LLM, and returns the formatted daily recap.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from config import settings


SYSTEM_PROMPT = """\
You are Hotel Intel, an AI assistant for luxury hotel general managers.
You produce concise, elegant daily recap briefings in Markdown format.

Style guidelines:
- Professional yet warm tone, befitting a luxury property
- Use the exact section structure provided
- Numbers should be formatted clearly (€1,234 not €1234)
- Highlight anomalies and actionable items
- Keep the executive summary to 2-3 sentences
- Use emoji sparingly for section headers as shown in the template
- Compare to previous day where data is available (use ↑/↓ arrows)
- Flag anything that needs GM attention in the Action Items section
"""


def build_prompt(data: dict[str, Any]) -> str:
    """Build the user prompt from processed data."""
    currency = data.get("currency", "€")
    date_str = data.get("date", "")
    
    try:
        dt = datetime.strptime(date_str, "%Y-%m-%d")
        formatted_date = dt.strftime("%A, %d %B %Y")
    except ValueError:
        formatted_date = date_str

    prompt = f"""Generate a daily recap briefing for **{data.get('hotel_name', 'the hotel')}** for **{formatted_date}**.

Use the following structured data to produce a complete Markdown briefing following our template structure.
Include all sections: Executive Summary, Key Metrics, Arrivals & Departures (with VIP details),
F&B Performance, Spa & Wellness, Villas, Incidents, Concierge Highlights, and Action Items.

Currency: {currency}

## RAW DATA

```json
{json.dumps(data, indent=2, default=str)}
```

## INSTRUCTIONS

1. Start with the header: ☀️ {data.get('hotel_name', '')} — {formatted_date}
2. Write a 2-3 sentence executive summary highlighting the most important points
3. Present Key Metrics in a clean table (Occupancy, ADR, RevPAR, Room Revenue, Total Revenue) with vs previous day
4. Detail arrivals/departures with VIP spotlight
5. F&B: table with outlet performance + today's lookahead
6. Spa: metrics table + utilization
7. Villas: occupancy status and details
8. Incidents: list with status icons (🔴 open, 🟡 in progress, 🟢 resolved)
9. Concierge highlights and notable arrangements
10. End with prioritized Action Items (🔴 urgent, 🟡 important, 🔵 standard)
11. Footer with generation timestamp and data sources

Be specific with names, room numbers, and details from the data. Don't invent data not present.
"""
    return prompt


def generate_recap(data: dict[str, Any], provider_override: str | None = None) -> str:
    """
    Generate the daily recap using the configured LLM provider.

    Args:
        data: Processed summary dict from processor.
        provider_override: Override LLM_PROVIDER from config.

    Returns:
        Formatted Markdown recap string.
    """
    from llm import get_provider

    provider_name = provider_override or settings.LLM_PROVIDER
    llm = get_provider(provider_name)

    prompt = build_prompt(data)
    recap = llm.generate(prompt=prompt, system_prompt=SYSTEM_PROMPT)

    # Append generation footer
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    sources = ", ".join(data.get("data_sources", []))
    footer = f"\n\n---\n*Generated by Hotel Intel · {timestamp} · Data sources: {sources}*"

    return recap + footer
